app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/lang/{lang}', function ($lang)
{
    session(['lang' => $lang]);
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'file', 'as' => 'file.'], function () {
    Route::get('/thumb/{dimensions}', ['as' => 'thumbnail', 'uses' => 'FileController@generateThumbnail']);
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'DashboardController@index']);
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function ()
    {
        Route::group(['prefix' => 'role', 'as' => 'roles.'], function ()
        {
            Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\RoleController@manage']);
            Route::post('/add', ['as' => 'add', 'uses' => 'Dashboard\RoleController@add']);
            Route::get('/add', ['as' => 'addform', 'uses' => 'Dashboard\RoleController@addView']);
            Route::delete('/{role}', ['as' => 'delete', 'uses' => 'Dashboard\RoleController@delete']);
            Route::get('/{role}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\RoleController@deleteConfirm']);
            Route::get('/{role}', ['as' => 'view', 'uses' => 'Dashboard\RoleController@view']);
            Route::post('/{role}', ['as' => 'edit', 'uses' => 'Dashboard\RoleController@edit']);
            Route::delete('/{role}/perm', ['as' => 'delperm', 'uses' => 'Dashboard\RoleController@delPermission']);
            Route::post('/{role}/perm', ['as' => 'addperm', 'uses' => 'Dashboard\RoleController@addPermission']);
        });
        Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\UserController@manage']);
        Route::delete('/{user}', ['as' => 'delete', 'uses' => 'Dashboard\UserController@delete']);
        Route::get('/{user}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\UserController@deleteConfirm']);
        Route::get('/{user}', ['as' => 'view', 'uses' => 'Dashboard\UserController@view']);
        Route::post('/{user}', ['as' => 'edit', 'uses' => 'Dashboard\UserController@edit']);
        Route::delete('/{user}/role', ['as' => 'delrole', 'uses' => 'Dashboard\UserController@removeRole']);
        Route::post('/{user}/role', ['as' => 'addrole', 'uses' => 'Dashboard\UserController@addRole']);
    });
    Route::group(['prefix' => 'participant', 'as' => 'participants.'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\ParticipantController@manage']);
        Route::post('/add', ['as' => 'add', 'uses' => 'Dashboard\ParticipantController@add']);
        Route::get('/add', ['as' => 'addform', 'uses' => 'Dashboard\ParticipantController@addView']);
        Route::delete('/{participant}', ['as' => 'delete', 'uses' => 'Dashboard\ParticipantController@delete']);
        Route::get('/{participant}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\ParticipantController@deleteConfirm']);
        Route::get('/{participant}', ['as' => 'view', 'uses' => 'Dashboard\ParticipantController@view']);
        Route::post('/{participant}', ['as' => 'edit', 'uses' => 'Dashboard\ParticipantController@edit']);
        Route::post('/{participant}/manager', ['as' => 'addmanager', 'uses' => 'Dashboard\ParticipantController@addManager']);
        Route::delete('/{participant}/manager', ['as' => 'delmanager', 'uses' => 'Dashboard\ParticipantController@deleteManager']);
    });
});

Route::group(['prefix' => 'account', 'as' => 'auth.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\AuthController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\AuthController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\AuthController@showRegistrationForm']);
    Route::post('register', ['as' => 'register', 'uses' => 'Auth\AuthController@register']);

    // Password Reset Routes...
    Route::get('password/reset/{token?}', ['as' => 'password.reset', 'uses' => 'Auth\PasswordController@showResetForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\PasswordController@sendResetLinkEmail']);
    Route::post('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\PasswordController@reset']);
});

/*Route::group(['prefix' => 'api', 'as' => 'api.'], function () {
    Route::group(['prefix' => 'ajax', 'as' => 'ajax'], function() {
        Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
            Route::get('user', ['as' => 'user', 'uses' => 'API\AJAX\SearchController@usersByName']);
        });
    });
});*/

Route::get('/', ['uses' => 'ClubController@viewList']);
Route::get('/subclub/{subclub}', ['as' => 'viewSubClub', 'uses' => 'ClubController@viewSubClub']);
Route::get('/{club}', ['as' => 'view', 'uses' => 'ClubController@viewClub']);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
        @hasSection('title')
            @yield('title') - IMS
        @else
            IMS
        @endif
    </title>

    <!-- Styles -->
    <link rel="stylesheet" href="/css/app.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Roboto', sans-serif;
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
    @yield('extrahead')
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    IMS
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                    @if (Auth::user())
                        <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('auth.login') }}">@lang('auth.login_action')</a></li>
                        <li><a href="{{ route('auth.register') }}">@lang('auth.register_action')</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ route('auth.logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if(session('message_type') !== null)
        <div class="alert alert-{{ session('message_type') }}"><strong>{{ session('message_title') }}</strong>{{ session('message_message') }}</div>
    @endif

    @yield('beforeContent')

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
    @yield('extrabottom')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
@extends('layouts.app')

@section('beforeContent')
    <div class="content">
        {{--<div class="row">--}}
            <nav class="col-md-2 col-md-offset-1" style="max-width: 100%;">
                <ul class="nav nav-pills nav-stacked">
                    <li {{ Request::route()->getName() == 'dashboard.index' ? 'class=active' : ''}}><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                    <hr>
                    Admin things:
                    <li {{ (0 ===  strpos(Request::route()->getName(), 'dashboard.auth.') && !(0 ===  strpos(Request::route()->getName(), 'dashboard.auth.roles.'))) ? 'class=active' : ''}}><a href="{{ route('dashboard.auth.index') }}">User Management</a></li>
                    <li {{ 0 ===  strpos(Request::route()->getName(), 'dashboard.auth.roles.') ? 'class=active' : '' }}><a href="{{ route('dashboard.auth.roles.index') }}">Role Management</a></li>
                    <li {{ 0 ===  strpos(Request::route()->getName(), 'dashboard.participants.') ? 'class=active' : '' }}><a href="{{ route('dashboard.participants.index') }}">Participant Management</a></li>
                </ul>
                </ul>
            </nav>
            @yield('content2')
        {{--</div>--}}
    </div>
@endsection

@section('title')
    @hasSection('title2')
        @yield('title2') - Dashboard
    @else
        Dashboard
    @endif
@endsection