app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/lang/{lang}', function ($lang)
{
    session(['lang' => $lang]);
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'file', 'as' => 'file.'], function () {
    Route::get('/thumb/{dimensions}', ['as' => 'thumbnail', 'uses' => 'FileController@generateThumbnail']);
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'DashboardController@index']);
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function ()
    {
        Route::group(['prefix' => 'role', 'as' => 'roles.'], function ()
        {
            Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\RoleController@manage']);
            Route::post('/add', ['as' => 'add', 'uses' => 'Dashboard\RoleController@add']);
            Route::get('/add', ['as' => 'addform', 'uses' => 'Dashboard\RoleController@addView']);
            Route::delete('/{role}', ['as' => 'delete', 'uses' => 'Dashboard\RoleController@delete']);
            Route::get('/{role}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\RoleController@deleteConfirm']);
            Route::get('/{role}', ['as' => 'view', 'uses' => 'Dashboard\RoleController@view']);
            Route::post('/{role}', ['as' => 'edit', 'uses' => 'Dashboard\RoleController@edit']);
            Route::delete('/{role}/perm', ['as' => 'delperm', 'uses' => 'Dashboard\RoleController@delPermission']);
            Route::post('/{role}/perm', ['as' => 'addperm', 'uses' => 'Dashboard\RoleController@addPermission']);
        });
        Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\UserController@manage']);
        Route::delete('/{user}', ['as' => 'delete', 'uses' => 'Dashboard\UserController@delete']);
        Route::get('/{user}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\UserController@deleteConfirm']);
        Route::get('/{user}', ['as' => 'view', 'uses' => 'Dashboard\UserController@view']);
        Route::post('/{user}', ['as' => 'edit', 'uses' => 'Dashboard\UserController@edit']);
        Route::delete('/{user}/role', ['as' => 'delrole', 'uses' => 'Dashboard\UserController@removeRole']);
        Route::post('/{user}/role', ['as' => 'addrole', 'uses' => 'Dashboard\UserController@addRole']);
    });
    Route::group(['prefix' => 'participant', 'as' => 'participants.'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Dashboard\ParticipantController@manage']);
        Route::post('/add', ['as' => 'add', 'uses' => 'Dashboard\ParticipantController@add']);
        Route::get('/add', ['as' => 'addform', 'uses' => 'Dashboard\ParticipantController@addView']);
        Route::delete('/{participant}', ['as' => 'delete', 'uses' => 'Dashboard\ParticipantController@delete']);
        Route::get('/{participant}/delete', ['as' => 'deleteConfirm', 'uses' => 'Dashboard\ParticipantController@deleteConfirm']);
        Route::get('/{participant}', ['as' => 'view', 'uses' => 'Dashboard\ParticipantController@view']);
        Route::post('/{participant}', ['as' => 'edit', 'uses' => 'Dashboard\ParticipantController@edit']);
        Route::post('/{participant}/manager', ['as' => 'addmanager', 'uses' => 'Dashboard\ParticipantController@addManager']);
        Route::delete('/{participant}/manager', ['as' => 'delmanager', 'uses' => 'Dashboard\ParticipantController@deleteManager']);
    });
});

Route::group(['prefix' => 'account', 'as' => 'auth.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\AuthController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\AuthController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);

    // Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\AuthController@showRegistrationForm']);
    Route::post('register', ['as' => 'register', 'uses' => 'Auth\AuthController@register']);

    // Password Reset Routes...
    Route::get('password/reset/{token?}', ['as' => 'password.reset', 'uses' => 'Auth\PasswordController@showResetForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\PasswordController@sendResetLinkEmail']);
    Route::post('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\PasswordController@reset']);
});

/*Route::group(['prefix' => 'api', 'as' => 'api.'], function () {
    Route::group(['prefix' => 'ajax', 'as' => 'ajax'], function() {
        Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
            Route::get('user', ['as' => 'user', 'uses' => 'API\AJAX\SearchController@usersByName']);
        });
    });
});*/

Route::get('/', ['uses' => 'ClubController@viewList']);
Route::get('/subclub/{subclub}', ['as' => 'viewSubClub', 'uses' => 'ClubController@viewSubClub']);
Route::get('/{club}', ['as' => 'view', 'uses' => 'ClubController@viewClub']);

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Participant extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'firstname', 'lastname', 'birthday', 'gender',
    ];

    public function users()
    {
        return $this->belongsToMany('App\User')->withPivot('role_id');
    }

    public function name()
    {
        return $this->firstname . ' ' . $this->lastname;
    }
}

app/Http/Controllers/Dashboard/ParticipantController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Participant;
use App\User;
use App\Role;

class ParticipantController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function manage()
    {
        $this->authorize('global.participants.manage');
        return view('dashboard.data.participants.manage', [
            'participants' => Participant::all(),
        ]);
    }

    public function delete(Participant $participant)
    {
        $this->authorize('delete', $participant);
        $user->delete();
        flash_message("Success!", "Participant has been deleted successfully!", "success");
        return redirect()->route('dashboard.participants.index');
    }

    public function deleteConfirm(Participant $participant)
    {
        $this->authorize('delete', $participant);
        return view('dashboard.data.participants.delete', [
            'participant' => $participant,
        ]);
    }

    public function view(Participant $participant)
    {
        $this->authorize('edit', $participant);
        return view('dashboard.data.participants.view', [
            'participant' => $participant,
            'users' => User::all()->sortBy('name'),
            'roles' => Role::all()->sortBy('name'),
        ]);
    }

    public function add(Request $req)
    {
        $this->authorize('global.participants.create');
        Participant::create($req->all());
        flash_message("Success!", "Participant has been created successfully!", "success");
        return redirect()->route('dashboard.participants.index');
    }

    public function addView(Request $req)
    {
        return view('dashboard.data.participants.add');
    }

    public function edit(Request $req, Participant $participant)
    {
        $this->authorize('edit', $participant);
        $participant->firstname = $req->firstname;
        $participant->lastname = $req->lastname;
        $participant->birthday = $req->birthday;
        $participant->gender = $req->gender;
        $participant->save();
        flash_message("Success!", "Participant has been updated successfully!", "success");
        return redirect()->route('dashboard.participants.index');
    }

    public function deleteManager(Request $req, Participant $participant)
    {
        $this->authorize('edit', $participant);
        $participant->users()->detach($req->user);
        return "OK";
    }

    public function addManager(Request $req, Participant $participant)
    {
        $this->authorize('edit', $participant);
        $participant->users()->attach($req->user, ['role_id' => $req->role]);
        flash_message("Success!", "Manager for participant has been added successfully!", "success");
        return redirect()->route('dashboard.participants.view', $participant);
    }
}

resources/views/dashboard/data/participants/add.blade.php
@extends('layouts.dashboard')

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Add participant</div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('dashboard.participants.add') }}">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                            <label for="firstname" class="col-md-4 control-label">Firstname</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="{{ old('firstname') }}">

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                            <label for="lastname" class="col-md-4 control-label">Lastname</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="{{ old('lastname') }}">

                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
                            <label for="birthday" class="col-md-4 control-label">Birthday</label>

                            <div class="col-md-6">
                                <input id="birthday" type="date" class="form-control" name="birthday" value="{{ old('birthday') }}">

                                @if ($errors->has('birthday'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('birthday') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                            <label for="gender" class="col-md-4 control-label">Gender</label>

                            <div class="col-md-6">
                                <input id="gender" type="text" class="form-control" name="gender" value="{{ old('gender') }}">

                                @if ($errors->has('gender'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('gender') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-user"></i> Add
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/data/participants/delete.blade.php
@extends('layouts.dashboard')

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Delete {{ $participant->firstname . ' ' . $participant->lastname }}</div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('dashboard.participants.delete', $participant->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <div class="col-md-6 col-md-offset-2">
                            Are you sure you want to delete participant '{{ $participant->firstname . ' ' . $participant->lastname }}'?
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-btn fa-user"></i> Yes
                                </button>
                                <a href="{{ route('dashboard.participants.index') }}" class="btn btn-default">
                                    <i class="fa fa-btn fa-user"></i> No
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/data/participants/manage.blade.php
@extends('layouts.dashboard')

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Participant Management</div>

                <div class="panel-body">
                    <div class="btn-group" style="margin-bottom:10px;">
                        <a href="{{ route('dashboard.participants.add')}}" class="btn btn-default">Add participant</a>
                    </div>
                    <table class="table">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Birthday</th>
                            <th></th>
                         </tr>
                        @foreach ($participants as $participant)
                            <tr>
                                <td>{{ $participant->id }}</td>
                                <td>{{ $participant->firstname . ' ' . $participant->lastname }}</td>
                                <td>{{ $participant->gender }}</td>
                                <td>{{ $participant->birthday }}</td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                                            <span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                                            <li role="presentation"><a role="menuitem" href="{{ route('dashboard.participants.view', $participant->id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>Edit</a></li>
                                            <li role="presentation"><a role="menuitem" href="{{ route('dashboard.participants.deleteConfirm', $participant->id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/data/participants/view.blade.php
@extends('layouts.dashboard')

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Edit {{ $participant->name() }}</div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('dashboard.participants.edit', $participant->id) }}">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                            <label for="firstname" class="col-md-4 control-label">Firstname</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="{{ $participant->firstname }}">

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                            <label for="lastname" class="col-md-4 control-label">Lastname</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="{{ $participant->lastname }}">

                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
                            <label for="birthday" class="col-md-4 control-label">Birthday</label>

                            <div class="col-md-6">
                                <input id="birthday" type="date" class="form-control" name="birthday" value="{{ $participant->birthday }}">

                                @if ($errors->has('birthday'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('birthday') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                            <label for="gender" class="col-md-4 control-label">Gender</label>

                            <div class="col-md-6">
                                <input id="gender" type="text" class="form-control" name="gender" value="{{ $participant->gender }}">

                                @if ($errors->has('gender'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('gender') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label">Managers</label>
                            <div class="col-md-6">
                                @foreach($participant->users as $user)
                                    <li>{{ $user->name }} ({{ App\Role::find($user->pivot->role_id)->name }}) <a href="#" class="btn btn-danger btn-xs" onclick="$.ajax({
    url: '{{ route('dashboard.participants.addmanager', $participant->id) }}' + '?user={{ $user->id }}',
    type: 'DELETE',
    success: function(result) {
        location.reload();
    }
}); return true;"><span class="glyphicon glyphicon-trash"></span></a></li>
                                @endforeach
                                <br>
                                <button type="button" class="btn btn-defaults" data-toggle="modal" data-target="#AddManager">Add Manager</button>
                                {{--<div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add Role<span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        @foreach($allRoles as $role)
                                            <li><a href="#" onclick="$.ajax({
    url: '{{ route('dashboard.auth.addrole', $user->id) }}' + '?id={{ $role->id }}',
    type: 'POST',
    success: function(result) {
        location.reload();
    }
}); return true;">{{ $role->name }}</a></li>
                                        @endforeach
                                    </ul>
                                </div>--}}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-user"></i> Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="AddManager" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <form class="form-horizontal" role="form" method="POST" action="{{ route('dashboard.participants.addmanager', $participant->id) }}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Manager for {{ $participant->name() }}</h4>
                </div>
                <div class="modal-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="user" class="col-md-4 control-label">User</label>
                        <div class="col-md-6">
                            <select id="user" name="user" class="selectpicker" data-live-search="true">
                                @foreach($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="role" class="col-md-4 control-label">Role</label>
                        <div class="col-md-6">
                            <select id="role" name="role" class="selectpicker" data-live-search="true">
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Add Manager</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('extrahead')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
@endsection

@section('extrabottom')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
@endsection